# 3

add_picture:
  path: /add-picture/{action}/{number}
  defaults: { _controller: "ArtMainBundle:Main:addPicture" }
  requirements:
    action: like|dislike|self
    number: \d+

# 2

export:
  path: /export/{user}
  defaults: { _controller: "ArtMainBundle:Main:export" }
  requirements:
    user: \d+

update_counters:
  path: /ajax/update-counters
  defaults: { _controller: "ArtMainBundle:Main:updateCounters" }

mark:
  path: /mark/{step}
  defaults: { _controller: "ArtMainBundle:Main:mark" }
  requirements:
    mark: \d+

check_picture:
  path: /check-picture/{number}
  defaults: { _controller: "ArtMainBundle:Main:checkPicture" }

# 1

admin:
  path: /admin
  defaults: { _controller: "ArtMainBundle:Main:admin" }

finish:
  path: /finish
  defaults: { _controller: "ArtMainBundle:Main:finish" }

pictures:
  path: /{page}
  defaults: { _controller: "ArtMainBundle:Main:pictures", page: 1 }
  requirements:
    page: \d