parameters:
#  empty

services:
  customer_hunt.controller_listener:
    class: Art\MainBundle\EventListener\ControllerListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
